# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/auth/casbin" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/handler" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/logrusx" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/zapx" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/logx/zerologx" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/rest/registry/etcd" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/router/chi" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/router/gin" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/router/mux" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/stores/clickhouse" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/zrpc/registry/consul" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/zrpc/registry/nacos" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/zrpc/registry/polaris" # Location of package manifests
    schedule:
      interval: "daily"
